name: Build and Push Dev Docker Image

on:
  push:
    paths:
      - '**.go'
      - 'Dockerfile'
      - 'entrypoint.sh'
      - 'healthcheck.sh'
      - 'go.mod'
      - 'go.sum'
    branches: [ main ]
  pull_request:
    paths:
      - '**.go'
      - 'Dockerfile'
      - 'entrypoint.sh'
      - 'healthcheck.sh'
      - 'go.mod'
      - 'go.sum'
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit message
        id: commit
        run: |
          echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.commit.outputs.sha_short }}
            ghcr.io/${{ github.repository }}:latest